config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :vehicles

  root  'static_pages#home'
  
  get 'static_pages/home'
  match '/register',  to: 'users#new',            via: 'get'
  match '/login',     to: 'sessions#new',         via: 'get'
  match '/logout',    to: 'sessions#destroy',     via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :vehicles

	before_save { self.email = email.downcase }
	before_create :create_remember_token

	validates :name, presence: true, length: { maximum: 60 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates(:email, presence: true, format: { with: VALID_EMAIL_REGEX },
		uniqueness: { case_sensitive: false })
	has_secure_password
	validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
	belongs_to :user
	  validates :user_id, presence: true
	  validates :licence_plate, presence: true, length: {maximum: 10}, uniqueness: { case_sensitive: false }
	  validates :make, presence: true
	  validates :year, length: { maximum:4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      login user
      redirect_to user
     else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
	
  def new
  	@user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Vehicle Registration App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def new
  	  	@vehicle = Vehicle.new
  end

  def show
    @vehicle = Vehicle.find(params[:id])    
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      flash[:success] = "New vehicle saved!"
      @user = User.find(vehicle.user_id)
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  	@vehicle = Vehicle.find(params[:id])
  end

  def update
  	@vehicle = Vehicle.find(params[:id])
    if @vehicle.update_attributes(vehicle_params)
       flash[:success] = "Profile updated"
       redirect_to users_path 
    else
      render 'edit'
    end
  end

  def destroy
  	vehicle.find(params[:id]).destroy
    flash[:success] = "Vehicle deleted."
    redirect_to users_path
  end

  def index
    @vehicle = Vehicles.all
  end

  private

    def vehicle_params
      params.require(:vehicle).permit(:licence_plate, :make, :model,
                                   :colour, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def logout
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "Vehicle Registration Application" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <% if signed_in? %>
                <li><%= link_to "Logout", logout_path, method: "delete" %></li>
              <% else %>
                <li><%= link_to "Login",   login_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @vehicles.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@vehicle.errors.count, "error") %>.
    </div>
    <ul>
    <% @vehicle.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Vehicle Registration Application Home Page</h1>
<div class="center hero-unit">
  <h1>Welcome to the Vehicle Registration Application Home Page</h1>
  <p>  </p>

  <%= link_to "Register now!", register_path, class: "btn btn-large btn-primary" %>
 <p>  </p>
 <p>  </p>
  <p>Are you an existing user?  <%= link_to "Login", login_path, class: "btn btn-large btn-primary" %></p>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<h1>Register</h1>
<p NOTE : Email and password are required fields /p>

<div class="row">
	<div class="span6 offset3">
	  <%= form_for(@user) do |f| %>
	 	<%= render 'shared/error_messages' %>
		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :street %>
		<%= f.text_field :street %>

		<%= f.label :city %>
		<%= f.text_field :city %>

		<%= f.label :province %>
		<%= f.text_field :province %>

		<%= f.label :postcode %>
		<%= f.text_field :postcode %>

		<%= f.label :phone %>
		<%= f.text_field :phone %>

		<%= f.submit "register", class: "btn btn-large btn-primary" %>
	<% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h2> Hello <%= @user.name %> </h2>
<p><%= link_to "Add new vehicle", '/vehicles/new' %></p>

<% if @user.vehicles.size == 0 %>
	<p>No vehicles registered</p>
<% else %>
  <table>
	<tr>
		<th>Licence Plate</th>
		<th>Make</th>
		<th>Model</th>
		<th>Colour</th>
		<th>Year</th>
		<th>Edit</th>
		<th>Remove</th>
	</tr>
	<% v = @user.vehicles.all do |vehicle| %>
	  <tr>
		<td><%= v.licence_plate %></td>
		<td><%= v.make %></td>
		<td><%= v.model %></td>
		<td><%= v.colour %></td>
		<td><%= v.year %></td>
		<td><%= link_to "Edit", edit_vehicles_path(v) %></td>
		<td><%= link_to "Remove", v, method: :delete,
							 data: { confirm: "You sure?" } %></td>
	  </tr>
	<% end %>
  </table>
<% end %>

app/views/vehicles/edit.html.erb
<% provide(:title, "Edit Vehicle") %>
<h1>Update your vehicle information</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@vehicle) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :Licence %>
      <%= f.text_field :licence_plate %>

      <%= f.label :make %>
      <%= f.password_field :make %>

      <%= f.label :model %>
      <%= f.text_field :model %>

      <%= f.label :colour %>
      <%= f.text_field :colour %>

      <%= f.label :year %>
      <%= f.text_field :year %>

      <%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/vehicles/new.html.erb
<% provide(:title, 'Add vehicle') %>
<h1>Add new vehicle</h1>
<p NOTE : Licence plate and make are required fields /p>

<div class="row">
	<div class="span6 offset3">
	  <%= form_for(@vehicle) do |v| %>

		<%= v.label :Licence %>
		<%= v.text_field :licence_plate %>

		<%= v.label :make %>
		<%= v.text_field :make %>

		<%= v.label :model %>
		<%= v.text_field :model %>

		<%= v.label :colour %>
		<%= v.text_field :colour %>

		<%= v.label :year %>
		<%= v.text_field :year %>

		<%= v.submit "Add Vehicle", class: "btn btn-large btn-primary" %>
	<% end %>
  </div>
</div>

app/views/vehicles/show.html.erb
<h1>Vehicles#show</h1>
<p>Find me in app/views/vehicles/show.html.erb</p>